import Todo from './models/todo';

export const mockTasks: Todo[] = [
  {
    id: 1,
    text: 'continue working on the project',
    done: false,
    isImportant: true,
    isFavourite: true,
    message: 'ezt mindenképp meg kell csináld',
  },
  {
    id: 2,
    text: 'vizsgára tanulás',
    done: false,
    isImportant: true,
    isFavourite: true,
    message: '',
  },
  {
    id: 3,
    text: 'beadandó elkezdése',
    done: false,
    isImportant: true,
    isFavourite: false,
    message: '',
  },
  {
    id: 4,
    text: 'mosogatás',
    done: true,
    isImportant: true,
    isFavourite: false,
    message: '',
  },
  {
    id: 5,
    text: 'ruha hajtogatás',
    done: false,
    isImportant: false,
    isFavourite: false,
    message: 'anyu nem lesz boldog ha nem csinálod meg',
  },
  {
    id: 6,
    text: '1 rész a sorozatból',
    done: false,
    isImportant: false,
    isFavourite: true,
    message: '',
  },
  {
    id: 7,
    text: 'olvass legalább 10 oldalt',
    done: false,
    isImportant: false,
    isFavourite: false,
    message: '',
  },
  {
    id: 8,
    text: 'kicserélni az elemet a kis lámpában',
    done: false,
    isImportant: false,
    isFavourite: false,
    message: '',
  },
];
