import Week from './models/week';

export const mockWeeks: Week[] = [
  {
    id: 202503,
    name: 'Default week',
    days: [
      {
        id: 1,
        name: 'Monday',
        tasks: [
          {
            id: 11234,
            text: 'dimod beadandó megvédése 11.20',
            done: true,
            isImportant: true,
            isFavourite: false,
            message: '',
          },
          {
            id: 253,
            text: 'algo vizsga gyak',
            done: true,
            isImportant: true,
            isFavourite: false,
            message: '',
          },
          {
            id: 323532,
            text: 'edzés',
            done: true,
            isImportant: false,
            isFavourite: true,
            message: 'kardiot ne felejtsd el!!',
          },
          {
            id: 41234,
            text: 'projekt munka',
            done: true,
            isImportant: false,
            isFavourite: true,
            message: 'kene haladni ha lesz ido ra',
          },
        ],
      },
      {
        id: 2,
        name: 'Tuesday',
        tasks: [
          {
            id: 1645,
            text: 'algo vizsga',
            done: true,
            isImportant: true,
            isFavourite: false,
            message: '4 vagy 5 kell',
          },
          {
            id: 214,
            text: 'MOSOGASS 💀💀💀',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: 'CSINÁLD MÁR MEG...',
          },
          {
            id: 367345,
            text: 'mosás 18.00',
            done: true,
            isImportant: true,
            isFavourite: true,
            message: 'ne felejtsd el legyszike :)',
          },
          {
            id: 41234,
            text: 'bevásárlás - lidl',
            done: true,
            isImportant: true,
            isFavourite: true,
            message: 'shopping list notionben',
          },
          {
            id: 54786,
            text: 'projekt munka',
            done: true,
            isImportant: false,
            isFavourite: true,
            message: 'ha lesz ido ra',
          },
        ],
      },
      {
        id: 3,
        name: 'Wednesday',
        tasks: [
          {
            id: 12345,
            text: 'projekt munka',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
          {
            id: 245678,
            text: 'edzés',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
          {
            id: 32845,
            text: 'főzés',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
          {
            id: 45687,
            text: 'bevásárlás - tesco',
            done: false,
            isImportant: false,
            isFavourite: true,
            message: '',
          },
        ],
      },
      {
        id: 4,
        name: 'Thursday',
        tasks: [
          {
            id: 16785,
            text: 'MOSOGASS 💀💀💀',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: 'NE LEGYÉL LUSTAAAA',
          },
          {
            id: 21023,
            text: 'projekt munka',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
          {
            id: 30123,
            text: 'edzés',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
        ],
      },
      {
        id: 5,
        name: 'Friday',
        tasks: [
          {
            id: 15678,
            text: 'projekt munka',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
          {
            id: 212345,
            text: 'edézs',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
          {
            id: 362323,
            text: 'órarend összeállítás',
            done: false,
            isImportant: true,
            isFavourite: false,
            message: '',
          },
        ],
      },
      {
        id: 6,
        name: 'Saturday',
        tasks: [
          {
            id: 14568,
            text: 'MOSOGASS 💀💀💀',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: 'ha skippeled +1 lábnap',
          },
          {
            id: 2453,
            text: 'projekt munka',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
          {
            id: 31234,
            text: 'séta',
            done: false,
            isImportant: true,
            isFavourite: false,
            message: 'ha mar rest day van mozogj valamit :3',
          },
          {
            id: 42345457,
            text: 'órarend egyeztetés patyival',
            done: false,
            isImportant: false,
            isFavourite: false,
            message: '',
          },
        ],
      },
      {
        id: 7,
        name: 'Sunday',
        tasks: [
          {
            id: 1123457,
            text: 'projekt munka',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
          {
            id: 223434567,
            text: 'séta',
            done: false,
            isImportant: true,
            isFavourite: false,
            message: 'ha már rest day van mozogj valamit :3',
          },
          {
            id: 31234567,
            text: 'órarend egyeztetés zolival',
            done: false,
            isImportant: false,
            isFavourite: false,
            message: '',
          },
          {
            id: 456712,
            text: 'kövi heti todos összeállítása',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
          {
            id: 556745,
            text: 'kövi heti shopping list összeállítása',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
        ],
      },
    ],
    isDeafult: true,
  },
  {
    id: 1,
    name: 'Holidays weeks',
    days: [
      {
        id: 1,
        name: 'Monday',
        tasks: [
          {
            id: 16795,
            text: 'ne rugj be pls',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
        ],
      },
      {
        id: 2,
        name: 'Tuesday',
        tasks: [
          {
            id: 11234,
            text: 'ne rugj be pls',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
        ],
      },
      {
        id: 3,
        name: 'Wednesday',
        tasks: [
          {
            id: 15678,
            text: 'ne rugj be pls',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
        ],
      },
      {
        id: 4,
        name: 'Thursday',
        tasks: [
          {
            id: 1231,
            text: 'ne rugj be pls',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
        ],
      },
      {
        id: 5,
        name: 'Friday',
        tasks: [
          {
            id: 14134623456,
            text: 'ne rugj be pls',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
        ],
      },
      {
        id: 6,
        name: 'Saturday',
        tasks: [
          {
            id: 156787,
            text: 'ne rugj be pls',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
        ],
      },
      {
        id: 7,
        name: 'Sunday',
        tasks: [
          {
            id: 101236,
            text: 'ne rugj be pls',
            done: false,
            isImportant: true,
            isFavourite: true,
            message: '',
          },
        ],
      },
    ],
    isDeafult: false,
  },
];
